// <auto-generated />
using AutoTravian.UI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoTravian.UI.Migrations
{
    [DbContext(typeof(BuildingDbContext))]
    [Migration("20230114090659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("AutoTravian.UI.Models.Entities.BuildingEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Production")
                        .HasColumnType("REAL");

                    b.Property<float>("ProductionNextLevel")
                        .HasColumnType("REAL");

                    b.Property<int>("VilageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("BuildingTable");
                });
#pragma warning restore 612, 618
        }
    }
}
